---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata: 
 name: "ibm-privileged-clusterrole-rolebinding"
 namespace: black
roleRef: 
 apiGroup: "rbac.authorization.k8s.io"
 kind: ClusterRole
 name: "ibm-privileged-clusterrole"
subjects: 
- apiGroup: "rbac.authorization.k8s.io"
  kind: Group
  name: "system:serviceaccounts:black"  
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata: 
 name: "ibm-privileged-clusterrole-rolebinding"
 namespace: white
roleRef: 
 apiGroup: "rbac.authorization.k8s.io"
 kind: ClusterRole
 name: "ibm-privileged-clusterrole"
subjects: 
- apiGroup: "rbac.authorization.k8s.io"
  kind: Group
  name: "system:serviceaccounts:white"  
