---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: default
  labels:
    app: collector
spec:
  type: NodePort
  selector:
    app: collector
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: collector

